name: deploy-code

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: number
        default: 16
      npm_command:
        required: true
        type: string
        default: echo "$comment is not present"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        if: ${{ inputs.node-version }} != ""
        with:
          node-version: 14
      - run: |
          if [[ ${{ inputs.npm_command }} != '' ]]
          then
            ${{ inputs.npm_command }}
          fi
      #- run: npm run build --if-present
      #- run: npm test
